apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "git-provider.fullname" . }}
  labels:
    {{- include "git-provider.labels" . | nindent 4 }}
data:
  GIT_PROVIDER_DEBUG: "{{ .Values.env.GIT_PROVIDER_DEBUG }}"
  GIT_PROVIDER_POLL_INTERVAL: "{{ .Values.env.GIT_PROVIDER_POLL_INTERVAL }}"
  GIT_PROVIDER_SERVICE_PORT_HACK: "{{ .Values.env.GIT_PROVIDER_SERVICE_PORT_HACK }}"
